this.leftAxisLayer = this.svg.append('g')
this.rightAxisLayer = this.svg.append('g')
this.bottomAxisLayer = this.svg.append('g')
this.plotArea = this.svg.append('g')
this.areaLayer = this.svg.append('g')
this.lineLayer = this.svg.append('g')
this.barLayer = this.svg.append('g')
this.symbolLayer = this.svg.append('g')
this.trackingLineLayer = this.svg.append('g')
this.render()
